DELETE FROM preguntas;
ALTER TABLE preguntas AUTO_INCREMENT = 1;


-- PREGUNTAS DE ACAMPADA

INSERT INTO preguntas (pregunta, resp1, resp2, resp3, resp4, fk_tematica, tipo) VALUES
('nombreJug LLEGA PARA UNA ACAMPADA DE FIN DE SEMANA, ¿DÓNDE MONTARÍA LA TIENDA?', 'En un lugar apartado en la espesura, alejado de los demás.', 'En un campamento animado con todas las comodidades.', ' ', ' ', 1, 'respFrases'),
('LA PAREJA DE ASPECTO ABURRIDO DE LA TIENDA DE AL LADO SUGIERE CENAR JUNTOS, ¿QUE HARÍA nombreJug ?', 'Aceptar la invitación tan sólo por cortesía', 'Rechazar la invitación, por embarazoso que sea.', ' ', ' ', 1, 'respFrases'),
('BIEN ENTRADA LA NOCHE, SE MONTA UNA FIESTA FUERA DE OTRA TIENDA, ¿QUE HARÍA nombreJug ?', 'Mosquearse y cantarles las cuarenta.', 'Sumarse a la fiesta y sacar sus mejores pasos de baile. ¡Yujuuu!.', ' ', ' ', 1, 'respFrases'),
('¿QUE ABRAZARÍA nombreJug PARA DORMIR EN UNA ACAMPADA?', 'cactus.png', 'escopeta.png', 'matamosquitos.png', 'oso.png', 1, 'respImg'),
('UN BUEN AMIG@ CELEBRA SU CUMPLEAÑOS...¡EN UN CAMPAMENTO NUDISTA! ¿QUE PENSARÍA nombreJug ?', '¡Toma ya!¡Qué grandísima idea!', 'Jolín, ¿Cómo me voy a librar de esta?', ' ', ' ', 1, 'respFrases'),
('AL LLEGAR AL CAMPAMENTO, LOS AMIG@S EMPIEZAN A JUGAR AL FÚTBOL DESNUDOS, ¿QUE PENSARÍA nombreJug ?', 'No he venido para esto.', 'Estupendo, me pido defensa. Tú ponte delantero', ' ', ' ', 1, 'respFrases'),
('¿QUIÉN RESCATARÍA A UN PÁJARO CAÍDO DEL NIDO PERDIDO EN EL CAMINO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('SI ENCONTRÁSEIS UN TERMITERO, ¿QUIÉN LO HUNDIRÍA DE UNA PATADA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIEN SERÍA MÁS VALIENTE DE ACERCARSE A UN ANIMAL SALVAJE?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIEN INTENTARÍA BESAR DE VERDAD A UNA RANA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('UNA TIENDA DE ACAMPADA NO ESTÁ ALINEADA CON EL RESTO, ¿QUIÉN LA HA MONTADO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('SI TODOS OS PERDIÉSEIS EN LA ESPESURA, ¿A QUIÉN LE ECHARÍAIS LA CULPA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN SE EMPEÑARÍA EN LLEVAR EL MAPA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN INTENTARÍA COLAR UN EDREDÓN Y UN COLCHÓN INFLABLE EN UNA ACAMPADA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN DISFRUTARÍA DE LA LIBERTAD DE PERDERSE EN LA NATURALEZA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN SE TUMBARÍA Y SE RENDIRÍA CINCO MINUTOS DESPUÉS DE PERDERSE EN LA NATURALEZA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('EN UNA EXCURSIÓN POR LA EXPESURA, EL GRUPO SE PIERDE Y EMPIEZAN A DESESPERARSE. ¿QUE HARÍA nombreJug ?', 'Quedarse atrás y esperar a que alguien tome el mando.', 'Tomar de inmediato el control de la situación.', ' ', ' ', 1, 'respFrases'),
('nombreJug, EL LÍDER DEL GRUPO, Y SU GRUPO DE CAMPAMENTO SE PIERDEN POR LA NATURALEZA, Y EMPIEZAN A DUDAR DE SU LIDERAZGO, ¿QUÉ HARÍA?', 'Decirles a tod@s que se callen y dejen de lloriquear.', 'Escuchar sus quejas y tratar de calmarlos.', ' ', ' ', 1, 'respFrases'),
('¿QUE COCINARÍA nombreJug EN LA FOGATA?', 'chuleton.png', 'pez.png', 'rana.png', 'verdura.png', 1, 'respImg'),
('¿QUIÉN QUEMARÍA EL MAPA PARA ENCENDER UNA FOGATA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('EN UNA SITUACIÓN DE FALTA DE AGUA ¿QUIÉN SERÍA EL PRIMERO EN BEBERSE SU PROPIO PIS?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('SI ATACASE UN OSO, ¿QUIÉN SE SACRIFICARÍA POR LOS DEMÁS?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN NO TENDRÍA REPAROS EN COMERSE LA COMIDA DE UNO DE SUS AMIGOS?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUE ÚNICA COSA QUERRÍA TENER nombreJug EN UNA SITUACIÓN DE SUPERVIVENCIA?', 'brujula.png', 'navaja.png', 'silla.png', 'oso.png', 1, 'respImg'),
('¿QUE ASPECTO TENDRÍA nombreJug DESPUÉS DE UN DÍA EN LA NATURALEZA?', 'bagabundo.png', 'aventurero.png', 'cansado.png', 'zombi.png', 1, 'respImg'),
('nombreJug DIRÍA: SIEMPRE QUE VOY DE ACAMPADA, ACABO...', 'Muy cansado y deseando acostarme.', 'Con la suficiente energía para darlo todo en la discoteca.', ' ', ' ', 1, 'respFrases'),
('¿QUIÉN SE BAJARÍA DEL JEEP PARA ACARICIAR A LOS LEONES?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN CORREGIRÍA LAS EXPLICACIONES DEL GUÍA DEL SAFARI?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('SI SE AVERIARA EL JEEP, ¿A POR QUIÉN IRÍAN PRIMERO LOS BUITRES?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN PENSARÍA QUE LAS HIENAS SE RÍEN A SU COSTA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿CON QUE SE EMOCIONARÍA MÁS nombreJug EN UN SAFARI?', 'rino.jpg', 'gacela.jpeg', 'elefantes.jpeg', 'navaja.png', 1, 'respImg'),
('EN UNA SALIDA, VEN QUE nombreJug SE HA QUEMADO CON EL SOL Y SE LO COMENTAN, ¿CÓMO REACCIONARÍA? ', 'Admitiendo que se ha quemado.', 'Diciendo: \'Esto mañana es moreno\'.', ' ', ' ', 1, 'respFrases'),
('¿QUIÉN PODRÍA DISTINGUIR UN MINERAL POCO COMÚN QUE ENCONTRÁSEIS POR EL CAMINO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN BROMEARÍA CON HABER VISTO UN OVNI POR EL CAMINO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN CREARÍA UN TEATRO DE MARIONETAS CON UNA ARDILLA MUERTA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN PROBARÍA LAS CACAS PARA BUSCAR A UN ANIMAL SALVAJE?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN PROBARÍA LAS CACAS PARA BUSCAR A UN ANIMAL SALVAJE?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN LOGRARÍA QUE SE LE POSASE UN RUISEÑOR EN EL DEDO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN DIRÍA QUE PODRÍA VENCER A UN OSO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN NO LE HABRÍA QUITADO AÚN EL PRECIO A SU EQUIPO DE CAMUFLAGE?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN LEVANTARÍA SU REFUGIO SOBRE UN HORMIGUERO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN ESCALARÍA UNA PARED DE ROCA AUNQUE LOS DEMÁS ENCONTRASEN OTRO CAMINO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('nombreJug DICE: \'NO SOBREVIRÍA NI UN FIN DE SEMANA SIN MI...\' ', 'Móvil.', 'Cervezita.', 'Libro favorito.', 'Play 4.', 1, 'respFrases'),
('¿QUIÉN SE COMERÍA UN ANIMAL ATROPELLADO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN SABRÍA CUÁLES SON LAS SETAS \'ALUCINÓGENAS\'?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN CAERÍA EN SU PROPIA TRAMPA ANTES QUE UN ANIMAL?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿CUÁL SERÍA LA SETA FAVORITA DE nombreJug ?', 'seta1.jpg', 'seta2.jpeg', 'seta3.jpg', 'seta4.jpg', 1, 'respImg'),
('¿QUE COMIDA SE LE HARÍA LA BOCA AGUA A nombreJug ?', 'chuleton.png', 'pez.png', 'seta1.jpg', 'verdura.png', 1, 'respImg'),
('EN UNA SALIDA AL RÍO, SE PROPONE IR EN CANOA ¿QUIÉN VOLCARÍA LA CANOA NADA MÁS SUBIRSE?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('EN UNA SALIDA AL RÍO, SE PROPONE IR EN CANOA ¿QUIÉN FINGIRÍA UNA LESIÓN PARA QUE LOS DEMÁS REMASEN POR ÉL?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('SI TODOS FUESEIS DE PESCA, ¿QUIÉN LLEVARÍA LA CAÑA MÁS LARGA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('EN UN DÍA DE PESCA, ¿QUIÉN LES METERÍA GUSANOS EN LOS PANTALONES A LOS DEMÁS?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('EN UN DÍA DE PESCA, nombreJug DIRÍA: \'¡MALDITA SEA, NO ME QUEDA CEBO! TENDRÉ QUE...\' ', 'sentarme', 'seguir durmiendo', 'ir a comprar', 'irme al bar', 1, 'respFrases'),
('¿LAS HISTORIAS DE QUIÉN MANDARÍAN AL RESTO AL PSIQUIATRA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN SE PERDERÍA POR EL BOSQUE DANDO SALTITOS TRAS UN CONEJITO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿DE QUE IRÍA LA HISTORIA JUNTO AL FUEGO DE LA ACAMPADA DE nombreJug ?', 'elefantes.jpeg', 'platillo.jpg', 'bambie.jpg', 'yeti.jpg', 1, 'respImg'),
('EL GRUPO VA A UNA SALIDA A LA MONTAÑA, ¿QUIÉN LLEGARÍA PRIMERO A LA CIMA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('EL GRUPO VA A UNA SALIDA A LA MONTAÑA, ¿QUIÉN PROVOCARÍA UNA AVALANCHA POR SU MAL COMPORTAMIENTO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('EN EL CAMPAMENTO, A LA HORA DE DORMIR, ¿QUIÉN PROPONDRÍA QUE TODOS SE DESNUDASEN AL DORMIR PARA COMPARTIR EL CALOR?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUE PINTA TENDRÍA nombreJug SUBIENDO A UNA MONTAÑA?', 'cansado.png', 'yeti.jpg', 'aventurero.png', 'zombi.png', 1, 'respImg'),
('EN EL CAMPAMENTO, A LA HORA DE DORMIR, ¿QUIÉN DESPERTARÍA A TODA LA ACAMPADA PORQUE HA VISTO ALGO RARO EN EL BOSQUE?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN LLEVARÍA GRANADAS DE MANO A UN FIN DE SEMANA DE SUPERVIVENCIA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN VOTARÍA POR IR A UN CAMPAMENTO NUDISTA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN USARÍA UNA ACAMPADA COMO EXCUSA PARA NO CAMBIARSE DE ROPA INTERIOR?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN APRENDERÍA POR LAS MALAS QUE NO HAY QUE ACARICIAR A LOS LOBOS?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN SE ASILVESTRARÍA EN UN CAMPAMENTO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUÉ HARÍA nombreJug EN UN LAGO?', 'castillo3.jpg', 'pescador1.jpeg', 'elefantes.jpeg', 'mates.jpg', 1, 'respImg'),
('nombreJug DICE: \'COMPAÑEROS, MIRAD MI...\'', 'oso.png', 'navaja.png', 'seta1.jpg', 'brujula.png', 1, 'respImg'),
('QUIÉN ES MÁS PROBABLE QUE SEA ARRASTRADO POR UN OSO?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿A QUÉ ANIMAL HABLARÍA nombreJug?', 'animal1.jpg', 'animal2.jpg', 'animal3.jpg', 'animal4.jpg', 1, 'respImg'),
('¿QUÉ ANIMAL SE LLEVARÍA nombreJug DE ACAMPADA PARA QUE LE HAGA COMPAÑÍA?', 'animal5.jpg', 'animal6.jpg', 'animal7.jpg', 'animal8.jpg', 1, 'respImg'),
('¿QUÉ TIPO DE MONO ESCOGERÍA nombreJug COMO MEJOR AMIGO?', 'animal9.jpg', 'animal10.jpg', 'animal11.jpg', 'animal12.jpg', 1, 'respImg'),
('¿QUÉ AVE LE GUSTARÍA A nombreJug ENCONTRARSE EN UNA SALIDA?', 'ave1.jpg', 'ave2.jpg', 'ave3.jpg', 'ave4.jpg', 1, 'respImg'),
('¿A QUIÉN LE PILLARÍAN CONDONES EN LA MOCHILA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN ESTARÍA MÁS DÍAS SIN DUCHARSE?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN LLEVARÍA LOS PRISMÁTICOS?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('¿QUIÉN LE TEJERÍA A UN ANIMAL SALVAJE UN JERSEY DE BROMA?', ' ', ' ', ' ', ' ', 1, 'respJug'),
('DIBUJA A nombreJug CÓMO SI ETUVIESE DE ACAMPADA', ' ', ' ', ' ', ' ', 1, 'respFoto');



-- PREGUNTAS DE COLEGIO

INSERT INTO preguntas (pregunta, resp1, resp2, resp3, resp4, fk_tematica, tipo) VALUES
('¿QUIÉN HARÍA COMO SI HUBIESE TOCADO EL TIMBRE DEL RECREO EN MEDIO DE CLASE?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿A QUIÉN LE PROHIBIRÍAN UTILIZAR LA JABALINA?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN SERÍA EL MÁS EMPOLLÓN DE LA CLASE?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN TENDRÍA LAS RESTRICCIONES MÁS RARAS CON LA COMIDA?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('EN EL COMEDOR, ¿QUIÉN PREFERIRÍAS QUE NO SE ACERCASE A TU COMIDA?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN SALUDARÍA CON LA MANO A SU MAMÁ DESDE LA COLA DE LA CARRERA?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿CUÁL SERÍA LA MEJOR PRUEBA DE DEPORTE PARA nombreJug ?', 'carrera.jpg', 'piramideHumana.jpg', 'malabares.jpg', 'elefantes.jpeg', 2, 'respImg'),
('nombreJug DICE: \'CONSEGUÍ UNA MEDALLA DE ORO EN...\' ', 'Dar puñetazos.', 'El recreo.', 'Matemáticas.', 'Cagarla.', 2, 'respFrases'),
('nombreJug SE SUBE AL AUTOBÚS ESCOLAR Y SÓLO QUEDAN DOS ASIENTOS VACÍOS. ¿DÓNDE SE SENTARÁ? ', 'Con la temible pandilla del fondo.', 'Con el llorón de los mocos cayéndole a chorros.', ' ', ' ', 2, 'respFrases'),
('LA PANDILLA DE LOS MALOTES DE LA CLASE DE AL LADO EXIGE A nombreJug QUE LES ENSEÑE QUE LLEVA EN LA MOCHILA, ¿QUE HARÁ?', 'Abrir la mochila con la esperanza de que la pandilla deje de molestar.', 'Mandar a paseo a la pandilla y arriesgarse a llevarse un puñetazo.', ' ', ' ', 2, 'respFrases'),
('LA PANDILLA DE LOS MALOTES DE LA CLASE DE AL LADO ABRE UNA VENTANA Y DESAFÍA A nombreJug A TIRAR EL RADIO CASSETTE DE LA PROFESORA POR LA VENTANA, ¿QUE HARÍA?', 'Tirar el caset arriesgandose una expulsión del centro.', 'No hacerlo, y sublebarse a la pandilla.', ' ', ' ', 2, 'respFrases'),
('¿QUE GARABATEARÍA nombreJug EN UNA VENTANA DE AUTOBÚS EMPAÑADA?', 'cristalpene.jpg', 'cristalsol.jpg', 'cristalcorazon.jpg', 'cristalmano.jpeg', 2, 'respImg'),
('¿QUIÉN LLEVARÍA AL LÍMITE A UN PROFESOR A PROPÓSITO?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN SE LLEVARÍA MAL CON TODO EL COLEGIO?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN INTENTARÍA LIGAR CON UN PROFESOR EN PRÁCTICAS?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN CUIDARÍA DEL NUEVO Y ASUSTADO ALUMNO?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿CON QUE CLASE DISFRUTARÍA MÁS nombreJug ?', 'piramideHumana.jpg', 'globoterra.jpg', 'mates.jpg', 'microscopio.jpeg', 2, 'respImg'),
('¿QUE DIBUJARÍA nombreJug EN UN CUADERNO EN TIEMPOS LIBRES EN CLASE?', 'Un dibujo muy bulgar.', 'Un dibujo de un personaje de película o serie.', 'A su compañero de al lado.', 'Nada porque no tiene imaginación o no le gusta dibujar.', 2, 'respFrases'),
('¿QUIÉN HABRÍA LLEVADO EL PEOR PEINADO DE TODO EL COLEGIO?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN TENDRÍA TODAS LAS PAPELETAS PARA QUE EL PROFE LO TIRASE POR LA VENTANA?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN LE RECORDARÍA AL PROFE QUE NO HA MANDADO DEBERES?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN SE PEGARÍA LOS DEDOS CON PEGAMENTO EN UNA CLASE DE MANUALIDADES?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUE HARÍA nombreJug DURANTE EL RECREO?', 'bagabundo.png', 'elefantes.jpeg', 'malabares.jpg', 'mates.jpg', 2, 'respImg'),
('nombreJug DICE: \'RÁPIDO, EL PROFE NO ESTÁ, VAMOS A...\'', 'Dar la vuelta a todas las mesas.', 'Hablar.', 'Coger el móvil.', 'Repasar para el exámen de mañana.', 2, 'respFrases'),
('¿QUIÉN FALSIFICARÍA UNA NOTA DE SUS PADRES PARA NO HACER EDUCACIÓN FÍSICA?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('EN EL BALÓN PRISIONERO, ¿QUIÉN APUNTARÍA SIEMPRE A LA CARA?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN SE QUEDARÍA CLAVADO HACIENDO UN MORTAL?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN DARÍA LATIGAZOS CON SU TOALLA A LOS DEMÁS EN LAS DUCHAS?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN SE DORMIRÍA EN MEDIO DE UN EXÁMEN?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('EN UN INTERCAMBIO DE CLASE VIENE UN PROFE Y PONE UN EXÁMEN DE CASTIGO PORQUE LA CLASE ESTABA CHILLANDO, ¿COMO REACCIONARÍA nombreJug?', 'Quejándose al profesor diciendo que es injusto.', 'Sentandose y haciendo el exámen sin rechistar.', ' ', ' ', 2, 'respFrases'),
('¿QUIÉN PEDIRÍA IR AL BAÑO EN MITAD DE CLASE SÓLO PORQUE LA CLASE LE ESTE ABURRIENDO?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('nombreJug SE ENTERA QUE EN EL COMEDOR, SU PROFE ESTÁ COMIENDO SU PLATO FAVORITO MIENTRAS QUE A ÉL LE TOCA ACELGAS, ¿CÓMO REACCIONARÍA?', 'Montar un pollo y lanzarle las acelgas a la cabeza.', 'Comerse sus acelgas y hacer como si no se hubiese enterado.', ' ', ' ', 2, 'respFrases'),
('¿QUIÉN SE REIRÍA DE UN CHISTE MALO DEL PROFESOR?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN SE COMERÍA EL PEGAMENTO EN UNA CLASE DE MANUALIDADES?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN PONDRÍA LA EXCUSA MÁS CUTRE POR NO HABER HECHO LOS DEBERES?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('SI EL PROFESOR HICIESE UN EXÁMEN SORPRESA, ¿QUIÉN LO BORDARÍA?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('EN UN INTERCAMBIO DE CLASE, A nombreJug LE TIRA EL GRACIOSILLO DE CLASE SU ESTUCHE POR LA VENTANA, ¿CÓMO REACCIONARÍA?', 'Presentándoles a sus amigos puño derecho y puño izquierdo.', 'Esperar a que venga un profe para decirselo.', ' ', ' ', 2, 'respFrases'),
('¿QUIÉN SE CHIVARÍA DE SU MEJOR AMIGO PARA EVITAR UN CASTIGO?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿A QUIÉN PILLARÍAN PASANDO FOTOS CHUNGAS?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN SUSPENDERÍA UN EXÁMEN AÚN HABIENDO COPIADO EN EL EXÁMEN?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN APROBARÍA UN EXÁMEN DIFÍCIL HABIENDO ESTUDIADO SÓLO 5min ANTES DEL EXÁMEN?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('A nombreJug LE PILLA EL PROFE COPIANDO EN UN EXÁMEN, ¿CÓMO REACIONARÍA?', 'Tragarse el papelito de la chuleta antes de que venga y negar que ha copiado.', 'Admitir que ha copiado en el examen.', ' ', ' ', 2, 'respFrases'),
('¿QUIÉN LLORARÍA DE MENTIRA PARA LIBRARSE DE UN CASTIGO?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿DE QUIÉN MERECERÍA LA PENA COPIAR UN TRABAJO?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN ACTIVARÍA LA ALARMA DE INCENDIOS POR DIVERSIÓN?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN FINGIRÍA ESTA ENFERMO PARA PODER SALIR DE LA ESCUELA?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('nombreJug ESTA VIENDO QUE EL MALOTE DE LA CLASE VA A PEGAR A UN PEQUEÑAJO, ¿COMO REACCIONARÍA?', 'Hacer como si nada estuviera pasando.', 'Meterse en la pelea para salvar al pequeñajo.', ' ', ' ', 2, 'respFrases'),
('¿CUAL SERÍA LA ASIGNATURA QUE MÁS DETESTA nombreJug ?', 'Matemáticas.', 'Lengua.', 'Historia.', 'Dibujo.', 2, 'respFrases'),
('¿QUIÉN SERÍA EL TÍPICO QUE TIENE SU ESTUCHE LLENO DE FIRMAS O DIBUJITOS?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('EN EL AUTOBÚS ESCOLAR, A nombreJug LE TOCA SENTARSE AL LADO DEL CHICO DE LOS MOCOS COLGANDO Y SIN QUERER LE PRINGA DE MOCOS ¿QUE HARÁ?', 'Limpiarse y separarse tranquilamente con la esperanza de encontrar otro asiento.', 'Ponerse a gritar y avergonzar al niño delante de todo el autobús.', ' ', ' ', 2, 'respFrases'),
('EN EL AUTOBÚS ESCOLAR, TODO EL MUNDO EMPIEZA A CANTAR UNA CANCIÓN MUY CRUEL SOBRE EL MOCOSO DE CLASE, ¿QUE HARÁ nombreJug ?', 'Mandar callar a todos y de paso conseguir un nuevo y mocoso amigo.', 'Hacer como si no estuviera pasando.', ' ', ' ', 2, 'respFrases'),
('¿CUÁL SERÍA EL ESTUCHE DE nombreJug ?', 'estuche1.jpg', 'estuche2.jpg', 'estuche3.jpeg', 'estuche4.jpeg', 2, 'respImg'),
('¿CÓMO SERÍA LA CHULETA DE nombreJug ?', 'chuleta1.jpeg', 'chuleta2.jpeg', 'chuleta3.jpg', 'chuleta4.jpg', 2, 'respImg'),
('¿A QUIÉN LE MOLESTARÍA MÁS LA FRASE DE \'Justifica tu respuesta\' EN UN EXMANEN?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN PEDIRÍA IR AL BAÑO CÓMO EXCUSA DE DARSE UN PASEÍTO?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿A QUIÉN LE PILLARÍAN CON EL MÓVIL EN CLASE?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿CUÁL SERÍA LA EXCUSA DE nombreJug PARA JUSTIFICAR QUE NO HIZO LA TAREA?', 'El perro se comió la tarea', 'La tengo hecha en otro cuaderno que tengo en casa', 'Yo esque no vine ese día', 'Tengo más asignaturas', 2, 'respFrases'),
('¿QUIÉN TENDRÍA MÁS NOTAS EN LA AGENDA POR MAL COMPORTAMIENTO?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿A QUIÉN LE ROBARÍAN EL BOCATA DE LA MERIENDA?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('A LA HORA SIGUIENTE DEL RECREO, HAY EXAMEN, ¿QUÉ HARÍA nombreJug en el recreo?', 'Llevarse el libro para repasar', 'Jugar como un día más', ' ', ' ', 2, 'respFrases'),
('¿QUIÉN SERÍA EL QUÉ ESTARÍA MASCANDO CHICLE EN CLASE?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN TENDRÍA MÁS RETRASOS POR LLEGAR TARDE A LA ESCUELA?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN ESTARÍA MÁS DESPISTAD@ EN LAS CLASES?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN SERÍA EL QUE LLEVARÍA LA BOLA PARA JUGAR EN EL RECREO?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN APROBARÍA UN EXÁMEN COMPLICADO CON MAYOR FACILIDAD?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN ES MÁS PROBABLE QUE LLEGUE BORRACHO A CLASE?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿CUÁL SERÍA LA MERIENDA DEL RECREO DE nombreJug?', 'zumo.jpg', 'botella2.jpg', 'snack4.jpg', 'manzana.jpg', 2, 'respImg'),
('¿QUIÉN TENDRÍA MÁS POSIBILIDADES DE QUE LE ECHEN DE CLASE POR HABLAR?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('EN UN EXAMEN, ¿DE QUIÉN SE COPIARÍA nombreJug?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN SERÍA EL MÁS PELOTA DE LA CLASE?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('EL PROFESOR REPARTE LA CLASE EN GRUPOS PARA HACER EL PROYECTO, ¿QUÉ PAPEL TENDRÍA nombreJug?', 'El que lleva la cartulina y se le olvida', 'El que no hace nada', 'El que hace casi todo el trabajo', 'El que pasa a limpio el texto', 2, 'respFrases'),
('¿QUIÉN SE QUEJARÍA MÁS DE LA COMIDA DEL COMEDOR?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUIÉN PEDIRÍA MÁS EL TIPEX EN UN EXAMEN?', ' ', ' ', ' ', ' ', 2, 'respJug'),
('¿QUÉ ENTRETENIMIENTO PREPARARÍA nombreJug PARA LA SOBREMESA?', 'uno.jpg', 'spiner.jpg', 'greg.png', 'cristalsol.jpg', 2, 'respImg'),
('DIBUJA A nombreJug CÓMO SI ESTUVIESE EN CLASE DE MATEMÁTICAS', ' ', ' ', ' ', ' ', 2, 'respFoto');



-- PREGUNTAS DE PLAYA

INSERT INTO preguntas (pregunta, resp1, resp2, resp3, resp4, fk_tematica, tipo) VALUES
('¿PORQUE SENTIRÍA nombreJug MÁS CURIOSIDAD EN UNA PLAYA NUDISTA?', 'Por saber qué se siente al ir todo el día en pelotas.', 'Por el aspecto de tod@s sus amig@s en pelotas.', ' ', ' ', 3, 'respFrases'),
('ACABÁIS DE LLEGAR A LA PLAYA, Y VÉIS QUE LA PLAYA TIENE BANDERA AMARILLA, ¿QUE DIRÍA nombreJug ?', 'Pues nada, volvamos a casa.', 'Da igual, nos bañamos igualmente, ya que estamos aqui no nos podemos ir.', ' ', ' ', 3, 'respFrases'),
('¿QUIÉN LLEVARÍA EL BAÑADOR MÁS LLAMATIVO?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('ESTANDO EN LA PLAYA, UNO DEL GRUPO, LE HACE UNA AGUADILLA A nombreJug. ¿COMO REACCIONARÍA?', 'Devolviendole la aguadilla haciendole una peor.', 'Enfadándose un poco y pidiéndole que no lo vuelva a hacer', ' ', ' ', 3, 'respFrases'),
('EN LA PLAYA, VEN QUE nombreJug SE HA QUEMADO CON EL SOL Y SE LO COMENTAN, ¿CÓMO REACCIONARÍA? ', 'Admitiendo que se ha quemado.', 'Diciendo: \'Esto mañana es moreno\'.', ' ', ' ', 3, 'respFrases'),
('¿EN QUE TIPO DE PLAYA PREFERIRÍA ESTAR nombreJug ?', 'En una en la que haya buenas olas para jugar con ellas.', 'En una tranquila para poder nadar agusto.', ' ', ' ', 3, 'respFrases'),
('¿QUIEN SERÍA MÁS PROBABLE QUE LE PICARA UNA MEDUSA?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('EL GRUPO DECIDE HACER UNA PEQUEÑA PESCA POR DIVERSIÓN, Y SE PESCAN CANGREJOS ¿QUE DIRÍA nombreJug ?', 'Nos llevamos a casa los cangrejos, que en la paella están deliciosos.', 'Pero luego les devolvemos al agua, pobrecillos.', ' ', ' ', 3, 'respFrases'),
('¿QUIÉN SE QUEDARÁ MÁS TIEMPO EN LAS TOALLAS PARA VIGILAR QUE NADIE ROBE NADA MIENTRAS EL RESTO DEL GRUPO ESTA BAÑÁNDOSE?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('¿QUIÉN SE INTENTARÍA LIGAR AL SOCORRISTA?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('MIENTRAS EL GRUPO ESTÁ BAÑÁNDOSE, nombreJug DICE HABER VISTO UNA SIRENA ¿QUE HARÁ?', 'Ir a hacerse un selfie con la sirena con su cámara acuática.', 'Dejar los porros.', ' ', ' ', 3, 'respFrases'),
('¿QUIÉN SE LLEVARÍA DE CASA UNA CÁMARA ACUÁTICA PARA HACER FOTOS DENTRO DEL AGUA?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('¿QUIÉN SE COMPRARÍA UNA COLCHONETA EN LA TIENDA DE AL LADO DE LA PLAYA?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('¿QUIÉN PROPONDRÍA JUGAR A LAS PALAS?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('LA GENTE DE LA TOALLA DE AL LADO, EMPIEZA A PONER MÚSICA IRRITANTE A TODO VOLUMEN, ¿QUE HARÁ nombreJug ?', 'Ir a hablar con ellos pacíficamente para llegar a un acuerdo.', 'Esperar a que otra persona les diga algo.', ' ', ' ', 3, 'respFrases'),
('¿QUE SERÍA IMPRESCINDIBLE PARA ESTAR EN LA PLAYA PARA nombreJug ?', 'navaja.png', 'silla.png', 'oso.png', 'gorra.jpg', 3, 'respImg'),
('¿DÓNDE PREFERIRÍA COMER nombreJug ?', 'En la playa con bocatas o tapers traidos de casa.', 'En un restaurante o chiringuito de playa.', ' ', ' ', 3, 'respFrases'),
('¿QUIÉN SE COMPRARÍA LA TÍPICA COLCHONETA DE COCODRILO?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('DESPUÉS DE BAÑARSE nombreJug, ¿CÓMO SE SECARÍA?', 'Esperando a que el sol haga su función.', 'Secándose con su toalla.', ' ', ' ', 3, 'respFrases'),
('¿A QUIÉN LE MOLESTARÍA MÁS MANCHARSE CON ARENA?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('¿A QUIÉN LE DARÍA MÁS ASCO LAS ALGAS?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('DESPUÉS DE BAÑARSE nombreJug, ¿CÓMO SE SECARÍA?', 'Esperando a que el sol haga su función.', 'Secándose con su toalla.', ' ', ' ', 3, 'respFrases'),
('nombreJug DIRÍA: ESTARÍA TODO EL DÍA EN LA PLAYA SI NO FUERA PORQUE ME FALTA...', 'Mi nevera con mis cervezas.', 'La play.', 'La sombrilla', 'Mi crema solar', 3, 'respFrases'),
('¿QUIÉN ESTARÍA MÁS TIEMPO TOMANDO EL SOL?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('¿QUIÉN LLEVARÍA UNA SOMBRILLA CON LA BANDERA DE ESPAÑA PARA REIVINDICAR LA UNIDAD DE ESPAÑA?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('¿CÓMO SERÍA EL CASTILLO DE ARENA DE nombreJug ?', 'castillo1.jpg', 'castillo2.jpg', 'castillo3.jpg', 'castillo4.jpg', 3, 'respImg'),
('nombreJug ESTÁ TRANQUILAMENTE TUMBADO EN LA TOALLA CUANDO ALGUIEN LE PISA SIN QUERER AL PASAR, ¿CÓMO REACCIONARÍA?', 'Haciendole que pida disculpas por haberle pisado.', 'Haciéndose el despistado mirando hacia otro lado.', ' ', ' ', 3, 'respFrases'),
('¿QUIÉN NADARÍA MEJOR?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('¿QUIÉN JUGARÍA MEJOR A LAS PALAS?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('SI COMIÉRAIS EN UN CHIRINGUITO, QUE PEDIRÍA nombreJug ?', 'verdura.png', 'rana.png', 'pescador1.jpeg', 'seta4.jpg', 3, 'respImg'),
('SI SE ESTUVISE AHOGANDOSE UN NIÑO QUE HARÍA nombreJug', 'Llamar al socorrista.', 'Ir a rescatarlo.', 'Ir al bar a tomar algo.', 'Reírse de él.', 3, 'respFrases'),
('¿QUIÉN TENDRÍA MÁS POSIBILIDAD QUE LE AHOGARA UN PULPO?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('SI nombreJug MIENTRAS ESTÁ NADANDO VE UN TIBURÓN ACERCARSE, ¿QUE HARÍA?', 'Llamar al socorrista.', 'Saludarle.', 'Hacerse el muerto.', 'Correr por encima del agua.', 3, 'respFrases'),
('ALGUIEN PROPONE IRSE A UNA PLAYA NUDISTA, ¿QUE DIRÍA nombreJug ?', 'pff, esque a mi las salchichas no me van.', 'perfecto, así no mojo el bañador.', ' ', ' ', 3, 'respFrases'),
('EL GRUPO PROPONE JUGAR AL VOLEY PLAYA, ¿QUÉ DIRÍA nombreJug ?', 'Na, dejate de pelotitas, yo he venido a bañarme.', 'Venga, me pido portero.', ' ', ' ', 3, 'respFrases'),
('ALGUIEN DEL GRUPO PROPONE ALQUILAR UN BARCO, ¿QUÉ DIRÍA nombreJug ?', 'Me pido capitán.', 'Mejor no que contamina mucho.', ' ', ' ', 3, 'respFrases'),
('¿QUIÉN COMPRARÍA UNAS GAFAS DE SOL A UN VENDEDOR AMBULANTE DE LA PLAYA?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('SI ESTUVIÉSEIS JUGANDO CON UNA PELOTA INFLABLE EN EL AGUA, ¿QUIÉN SERÍA MÁS PROBABLE QUE LA PIERDA?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('¿QUE FLOTADOR TENDRÍA nombreJug ?', 'flotador1.jpeg', 'flotador2.jpeg', 'flotador3.jpg', 'flotador4.jpg', 3, 'respImg'),
('¿A QUIÉN LE APETECERÍA MÁS SURFEAR LAS OLAS?', ' ', ' ', ' ', ' ', 3, 'respJug'),
('ALGUIEN DEL GRUPO PROPONE HACER SUBMARINISMO, ¿QUÉ DIRÍA nombreJug ?', 'Genial, me encanta observar los corales y los peces', 'Ir vosotros, yo cuido la toalla', 'De una bro', 'Pff, esque nos podemos ahogar, es peligroso', 3, 'respJug'),
('DIBUJA A nombreJug CÓMO SI FUERA UN SURFERO PROFESIONAL', ' ', ' ', ' ', ' ', 3, 'respFoto');



-- PREGUNTAS DE POLICIA

INSERT INTO preguntas (pregunta, resp1, resp2, resp3, resp4, fk_tematica, tipo) VALUES
('¿QUIÉN EMPEZARÍA UNA BATALLA DE COMIDA?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN CONSEGUIRÍA QUE LAS COCINERAS LE DIESEN RACIÓN EXTRA?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN SE QUEJARÍA MÁS DE LA COMIDA DEL COMEDOR?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN ESCRIBIRÍA DESESPERADAMENTE SUS DEBERES ?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('SI nombreJug FUESE POLI, EN UN HOMICIDIO, ¿QUE HARÍA?', 'Dirigirse a la escena del crimen en busca de pistas.', 'Quedarse en el cordón policial gritando a todo el que se acerque.', ' ', ' ', 4, 'respFrases'),
('EN UN HOMICIDIO, EL JEFE DE POLICÍA DICE QUE ES EL CRIMEN MÁS SANGRIENTO QUE HA VISTO JAMÁS. ¿QUE HARÍA nombreJug ?', 'Entrar a verlo enseguida, puede con eso y con más.', 'Preguntar si puede buscar huellas dactilares en otra habitación.', ' ', ' ', 4, 'respFrases'),
('EN UN HOMICIDIO, LE PIDEN A nombreJug QUE FOTOGRAFÍE LA BRUTAL ESCENA DEL CRÍMEN, ¿QUE HARÍA?', 'Sacar una sola foto del cadáver, que es lo importante.', 'Catalogar todo detalle de la habitación.', ' ', ' ', 4, 'respFrases'),
('UN VECINO ESTÁ COLANDO BOLSAS DE DINERO EN SU CASA ¿QUE HARÍA nombreJug ?,', 'Llamar a la policía para chivarse', 'Salir a ver de que va la historia', ' ', ' ', 4, 'respFrases'),
('¿CÓMO SE ACERCARÍA nombreJug A UN SOSPECHOSO?', 'Iría a acusarlo abiertamente', 'Intentar sacarle pistas sin que se de cuenta', ' ', ' ', 4, 'respFrases'),
('EL SOSPECHOSO CONFIESA QUE ROBÓ EL DINERO PARA PAGAR UN TRATAMIENTO MÉDICO VITAL, ¿QUE HARÍA nombreJug ?', 'No diría nada, aunque no aprueba el robo', 'Delatarlo igualmente, ese tipo es un ladrón', ' ', ' ', 4, 'respFrases'),
('¿QUE OBJETO SOSPECHOSO DEL CRÍMEN LE GUSTARÍA ENCONTRAR A nombreJug ?', 'pistola.jpg', 'motosierra.jpg', 'seta3.jpg', 'cactus.png', 4, 'respImg'),
('SI TODOS FUÉSEIS POLIS, ¿QUIÉN DISPARARÍA ANTES DE PREGUNTAR?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN PEDIRÍA REFUERZOS PARA LIDIAR CON ALGUIEN QUE TIRA BASURA POR EL SUELO?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN SALDRÍA POR UNA VENTANA PARA HABLAR CON ALGUIEN EN EL ALFÉIZAR?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUE TIPO DE POLICÍA SERÍA nombreJug ?', 'poli1.png', 'poli2.png', 'poli3.png', 'poli4.png', 4, 'respImg'),
('nombreJug DICE: \'SI FUESE POLICÍA, ARRESTARÍA A TODO EL QUE...\'', 'Fume en la calle.', 'Deje medio limón en la nevera.', 'No recicle como es debido.', 'Vaya mal vestido.', 4, 'respFrases'),
('¿QUIÉN CONDENARÍA A CADENA PERPETUA A UN RATERO?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN CONTARÍA SECRETOS DE SUMARIO A SUS AMIGOS?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN INFLUIRÍA MÁS EN EL JURADO?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN DEJARÍA ESCAPAR A UN CRIMINAL POR SENTIRSE ATRAÍDO POR ÉL?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUE TIPO DE JURADO SERÍA nombreJug ?', 'jurado1.jpg', 'jurado2.jpg', 'jurado3.jpg', 'jurado4.jpg', 4, 'respImg'),
('nombreJug DICE: \'ME EXPULSARON DE LA COMISARÍA AL...\' ', 'Intentar ligar con el policía.', 'Mascar chicle en la comisaría.', 'Contar chistes al policía.', 'Tardar una hora en salir del baño.', 4, 'respFrases'),
('¿QUIÉN SE CREERÍA CAPAZ DE PLANEAR UN ATRACO A UN BANCO?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN LES SACARÍA LA LENGUA A LAS CÁMARAS DE VIGILANCIA?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('SI ROBÁRAIS UNA JOYERÍA, ¿QUIÉN SE GUARDARÍA LA MEJOR JOYA DEL BOTÍN?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN OLVIDARÍA DÓNDE DEJÓ EL COCHE TRAS UN ROBO PARA LA HUIDA?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUE TIPO DE LADRÓN SERÍA nombreJug ?', 'atraco1.jpg', 'atraco2.jpg', 'atraco3.jpg', 'atraco4.jpg', 4, 'respImg'),
('¿QUE SERÍA MÁS PROBABLE QUE ROBE nombreJug ?', 'matamosquitos.png', 'rana.png', 'gorra.jpg', 'oso.png', 4, 'respImg'),
('¿QUIÉN SE TOMARÍA MÁS EN SERIO LO DE AGENTE SECRETO QUE OLVIDARÍA SU NOMBRE?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN LLAMRÍA AL 112 PARA HACER UNA BROMA TELEFÓNICA?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN SUSPENDERÍA EL EXÁMEN PARA SER AGENTE SECRETO POR PONER SU NOMBRE EN EL EXÁMEN?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN REVELARÍA QUE ES POLICÍA EN CUANTO SE VIESE EN PELIGRO?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN TENDRÍA MÁS POSIBILIDADES DE HACER UN GRAN ROBO?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿EN QUIÉN CONFIARÍAIS PARA FUGAROS DE LA CÁRCEL?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN PREPARARÍA LOS BOCADILLOS PARA EL GRAN ROBO?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('SI ESTUVIÉSEIS EN LA CÁRCEL PLANEANDO FUGAROS, ¿EL TÚNEL DE QUIÉN LLEGARÍA AL COMEDOR DE LOS GUARDIAS?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('SI ESTUVIÉSEIS EN LA CÁRCEL PLANEANDO FUGAROS, ¿QUIÉN INTENTARÍA TENER CONFIANZA CON UN GUARDIA PARA QUE LE AYUDARA A ESCAPAR?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿CÓMO SE FUGARÍA nombreJug DE LA CÁRCEL?', 'atraco1.jpg', 'platillo.jpg', 'carrera.jpg', 'atraco2.jpg', 4, 'respImg'),
('¿QUÉ OBJETO USARÍA nombreJug PARA FUGARSE DE LA CÁRCEL?', 'navaja.png', 'seta1.jpg', 'escopeta.png', 'gorra.jpg', 4, 'respImg'),
('OS COMUNICAN QUE EL CRÍMEN SE PRODUZCO CON UN GUITARRAZO, Y MÁS TARDE, LE REMATARON CON UN VIOLÍN, ¿QUE DIRÍA nombreJug ?', 'Probablemente el asesino sea músico', 'mmm... Todo con cuerda', 'Supongo que el crimen se planeó con trabajo', 'Que forma más rara de matar a alguien', 4, 'respFrases'),
('QUIÉN ES MÁS PROBABLE QUE SEA DETENIDO POR ACOSAR A UN OFICIAL DE POLICIA?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN ES MÁS PROBABLE QUE SALGA ABSUELTO TRAS HABER COMETIDO UN ASESINATO?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿A QUIÉN ARRESTARÍAN EN UNA MANIFESTACIÓN?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN SE SALDRÍA DE UNA MANIFESTACIÓN ANTICAPITALISTA PARA IR A COMPRAR AL ZARA?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUIÉN SE HARÍA UN SELFIE DELANTE DE LOS ANTIDISTURBIOS?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('nombreJug DIRÍA: "SI REDACTASE UN CARTEL DE PROTESTA PONDRÍA"...', 'Los disléxicos también somos persianas', 'Prohibamos ya la tortilla sin cebolla', 'Acabemos con el hambre en el mundo ya!!', 'Expulsemos a los inmigrantes ilegales del país!!', 4, 'respFrases'),
('¿QUIÉN LE BAJARÍA LOS PANTALONES A UN POLICÍA?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('¿QUE ES MÁS PROBABLE QUE HAGA nombreJug EN UNA CÁRCEL?', 'Contar chistes a sus compañeros de celda', 'Leerse el libro del Quijote', 'Tatuarse en el cuerpo el mapa de la cárcel para poder escapar', 'Ver tutoriales de cocina para convertirse en un gran cociner@', 4, 'respFrases'),
('¿QUIÉN ES MÁS PROBABLE QUE MATE A ALGUIEN ACCIDENTALMENTE?', ' ', ' ', ' ', ' ', 4, 'respJug'),
('DIBUJA A nombreJug CÓMO SI FUESE UN POLICÍA CORRUPTO', ' ', ' ', ' ', ' ', 4, 'respFoto');



-- PREGUNTAS DE DEPORTES

INSERT INTO preguntas (pregunta, resp1, resp2, resp3, resp4, fk_tematica, tipo) VALUES
('¿QUIÉN SUGERIRÍA JUGAR A LA PETANCA?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('EN UN PARTIDO DE TENIS, ¿QUIÉN SERÍA EL MEJOR RECOGEPELOTAS?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('EL GRUPO DECIDE IR A HACER GOLF, ¿QUIÉN METERÍA MÁS HOYOS?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN PEDIRÍA AGUA PORQUE SE LE OLVIDÓ TRAER?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿A QUIÉN ES MÁS PROBABLE QUE SE LE VAYA LA PINZA EN UN PARTIDO DE VOLEIBOL?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN SE MARCARÍA EN PROPIA EN UN PARTIDO DE FÚTBOL?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN MARCARÍA MÁS CANASTAS?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿A QUIÉN SE LE ESCAPARÍA MÁS VECES LA PELOTA DE LA CANCHA?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN TENDRÍA MENOS POSIBILIDADES DE MARCAR UN GOL?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN SE CANSARÍA ANTES?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('EN UN PARTIDO DE FÚTBOL, ¿QUIÉN FALLARÍA A PORTERÍA VACÍA?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('EN UN PARTIDO DE FÚTBOL, ¿QUIÉN INSULTARÍA MÁS AL ÁRBITRO?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUÉ DEPORTE SE LE DARÍA MEJOR A nombreJug?', 'deportes1.jpg', 'deportes2.jpg', 'deportes3.jpg', 'deportes4.jpg', 5, 'respImg'),
('¿QUIÉN ES MÁS PROBABLE QUE GANE UNA MEDALLA OLÍMPICA?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN ES MÁS PROBABLE QUE HAGA PUÉNTING?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUÉ TIPO DE ZAPATILLAS LLEVARÍA nombreJug A UN PARTIDO DE FÚTBOL?', 'zapatillas1.jpg', 'zapatillas2.jpg', 'zapatillas3.jpg', 'zapatillas4.jpg', 5, 'respImg'),
('¿QUÉ TIPO DE BOTELLA LLEVARÍA nombreJug A HACER DEPORTE?', 'botella1.jpg', 'botella2.jpg', 'botella3.jpg', 'botella4.jpg', 5, 'respImg'),
('¿QUIÉN ESTARÍA MÁS TIEMPO EN EL BANQUILLO?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN INTENTARÍA LIGAR CON EL/LA ARBITR@?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿CUÁL SERÍA EL APERITIVO DE nombreJug?', 'snack1.jpg', 'snack2.jpg', 'snack3.jpg', 'snack4.jpg', 5, 'respImg'),
('nombreJug VA A UNA CANCHA DE FÚTBOL PERO ESTA LLENA DE NIÑOS, ¿QUÉ HARÍA?', 'Hacerse el macho e intentar echar a los niños', 'Ir a buscar otra pista libre', 'Irse al bar, ya bajará otro día ;) ;)', 'Esperar mientras "Los pilares de la Tierra"', 5, 'respFrases'),
('A nombreJug SE LE OLVIDA EL BALÓN EN SU CASA, ¿QUÉ HARÍA?', 'Comprarse otra', 'Ir al bar a por un pelotazo', 'Robársela a un niño pequeño', 'Acoplarse a alguien que ya estuviese jugando', 5, 'respFrases'),
('ALGUIEN DEL GRUPO CUELA LA PELOTA DE nombreJug EN UN ÁRBOL, ¿QUÉ HARÍA?', 'Escalar creyendose Spider-man y cogerla', 'Ir a por un oso panda y que escale y se la devuelva', 'Llamar a los bomberos como si de un gato se tratase', 'Coger el balón de otro niño y darle balonazos para que se caiga', 5, 'respFrases'),
('ALGUIEN PROPONE IR A JUGAR A LA PETANCA ¿QUE DIRÍA nombreJug?', 'No voy, esos es pa viejos', 'No puedo, no tengo raqueta', 'Vale, os voy a ganar a todos, mi abuelo fue campeón nacional', '¿Eso se come?', 5, 'respFrases'),
('¿QUIÉN GANARÍA EN UN COMBATE DE BOXEO?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN SERÍA EL ENTRENADOR DE nombreJug EN UN COMBATE DE BOXEO?', 'tyson.jpg', 'canguro.jpg', 'Clint.jpg', 'moe.jpg', 5, 'respImg'),
('¿QUIÉN FALLARÍA MÁS PRIMEROS SAQUES EN UN PARTIDO DE TENIS O PÁDEL?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN LEVANTARÍA MÁS HIERRO EN UN GINMASIO?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN IRÍA A UN GIMNASIO SOLO PARA LIGAR?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿A QUIÉN SE LE CAERÍA UNA PESA EN EL PIE POR MIRAR A ALGUIEN?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN IRÍA AL GIMNASIO SOLO POR EL POSTUREO?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN TENDRÍA MÁS MIEDO A PELEAR EN UN COMBATE DE BOXEO?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN ES MÁS PROBABLE QUE PINCHE LA PELOTA?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN ES MÁS PROBABLE QUE SEA EL MÁS ATLÉTICO?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('¿QUIÉN ES MÁS PROBABLE QUE SE CONVIERTA EN UNA ESTRELLA DEL DEPORTE?', ' ', ' ', ' ', ' ', 5, 'respJug'),
('DIBUJA A nombreJug CÓMO SI ESTUVIESE JUGANDO AL FÚTBOL UN DÍA DE LLUVIA', ' ', ' ', ' ', ' ', 5, 'respFoto');



-- PREGUNTAS DE VIAJE

INSERT INTO preguntas (pregunta, resp1, resp2, resp3, resp4, fk_tematica, tipo) VALUES
('UNA PERSONA MUY ATRACTIVA SE QUEDA DORMIDA SOBRE EL HOMBRO DE nombreJug, ¿QUE HARÁ?', 'Apartarla cuidadosamente por muy atractiva que sea.', 'Dejarla dormir plácidamente', ' ', ' ', 6, 'respFrases'),
('DURANTE UN VIAJE, nombreJug DESPIERTA SIN QUERER A UNA PERSONA QUE ESTABA AL LADO SUYO Y ESTE SE PONE A QUEJARSE A GRITOS POR DESPERTARLA ¿QUE HARÁ?', 'Explicarle con calma que fue sin querer.', 'Enfadarse y preguntarle quién demonios se cree que es', ' ', ' ', 6, 'respFrases'),
('DE VIAJE DE VACACIONES EN TREN, UN LOCO SE PONE A GRITAR, Y TODO EL VAGÓN SE LE QUEDA MIRANDO, ¿QUE HARÁ nombreJug ?', 'Seguir en su sitio, ¿Por qué tendría que moverse?', 'Coger las maletas y cambiar de vagón', 'Decirle al maquinista que pare el tren', 'Intentar razonar con el loco para ver si se calla', 6, 'respFrases'),
('¿QUIÉN LE MOLETARÍA MÁS A nombreJug TENER AL LADO EN UN VIAJE EN TREN?', 'it.jpg', 'gordo.jpg', 'alcoholico.jpg', 'zombi.png', 6, 'respImg'),
('¿QUIÉN TENDRÍA MÁS POSIBILIDADES DE OLVIDARSE DE LA MALETA EN CASA Y DARSE CUENTA EN EL TREN?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿QUIÉN TENDRÍA MÁS POSIBILIDADES DE CONOCER UNA CÁRCEL EXTRANJERA POR DENTRO?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('SI OS METIERAIS EN UN LÍO DURANTE LAS VACACIONES ¿QUIÉN LO SOLUCIONARÍA?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('nombreJug DICE: \'¡NO PUEDO SEGUIR EN ESTA HABITACIÓN NO TIENE...!\'', 'WI-FI', 'para cargar el móvil al lado de la mesilla de noche', 'sábanas en condiciones', 'juegos o libros', 6, 'respFrases'),
('¿QUIÉN PENSARÍA QUE EN EL EXTRANJERO TODO EL MUNDO INTENTARÍA ESTAFARLE?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿A QUIÉN LE ENTRARÍA CAGALERA CON SÓLO MIRAR LA COMIDA LOCAL?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿PARA QUÉ TIPO DE PROBLEMAS SERÍA nombreJug UN IMÁN?', 'problemas1.jpg', 'problemas2.jpg', 'problemas3.jpg', 'problemas4.jpg', 6, 'respImg'),
('¿QUIÉN PERDERÍA ANTES LA MALETA EN UN AVIÓN?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿QUIÉN ES MÁS PROBABLE QUE SALTE DE UN TREN EN MARCHA?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿QUIÉN ES MÁS PROBABLE QUE SE ESCABULLA DE UN VIAJE DE CHIC@S PARA COQUETEAR CON UN EXTRAÑO?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿CON QUIÉN PREFERIRÍA nombreJug IRSE DE VIAJE?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿CUÁL SERÍA EL VIAJE DE LOS SUEÑOS DE nombreJug ?', 'chabola.jpg', 'hawaii.jpg', 'monta.jpg', 'venecia.jpg', 6, 'respImg'),
('¿CUÁL SERÍA LA MALETA DE nombreJug ?', 'maleta1.jpg', 'maleta2.jpg', 'maleta3.jpg', 'maleta4.jpg', 6, 'respImg'),
('EN EL VIAJE, nombreJug EMPIEZA A CONTAR UNA HISTORIA, ¿SOBRE QUÉ IRÍA SU HISTORIA?', 'elefantes.jpeg', 'platillo.jpg', 'problemas4.jpg', 'carrera.jpg', 6, 'respImg'),
('¿QUIÉN ES MÁS PROBABLE QUE PIERDA EL TREN?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿QUIÉN VIAJARÍA EN UN ZEPPELIN?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿QUIÉN INTENTARÍA LIGAR CON UN/UNA AZAFAT@ DURANTE UN VIAJE?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿QUIÉN SE LLEVARÍA SU MASCOTA DE VIAJE?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿QUIÉN TENDRÍA MÁS POSIBILIDADES DE MAREARSE EN UN VIAJE?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿QUIÉN COMPRARÍA MÁS IMANES DEL SITIO DE DONDE HA ESTADO?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿QUIÉN TENDRÍA MÁS PAPELETAS PARA SER DEPORTADO DE UN PAÍS?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿QUÉ DIRÍA nombreJug CUANDO LE DICEN QUE SE VAN DE VACIONES A RUSIA?', '¡Ni hablar!, eso esta lleno de rojos', 'Bien, me gusta el buen vodka', 'Perfecto, vamos a la madre patria', '¿¡Rusia!, eso se come?', 6, 'respFrases'),
('¿A DÓNDE IRÍA nombreJug PARA EVITAR UNA OLA DE CALOR?', 'Jamaica, con la playita', 'Siberia, le apetece un poco de frío después de la ola de calor', 'Seguir su camino a Mordor, una ola de calor no debe parar su misión', 'Al polo norte para ver la aurora boreal', 6, 'respFrases'),
('¿CUÁL SERÍA LA COMIDA EXTRANJERA PREFERIDA DE nombreJug?', 'Haggis.jpg', 'sopa.jpg', 'helado.jpg', 'surstromming.jpg', 6, 'respImg'),
('¿QUIÉN ACABARÍA EN URGENCIAS POR UN COMA ETÍLICO EN UN VIAJE DEL COLEGIO?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('¿A QUIÉN SE LE OLVIDARÍA METER LOS BAÑADORES EN LA MALETA DE VIAJE A LA PLAYA?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('A nombreJug LE EMPIEZAN A HABLAR EN UN IDIOMA QUE NO ENTIENDE,¿COMO REACCIONARÍA?', 'Diría: "illo, que estas diciendo a mi no me hableh en shino a mi en andalúh"', 'Cogería el traductor e intentaría entablar una conversación', 'Diría: "¿Qué has dicho de mi madre?", y le pegaría', 'Saldría corriendo por si el extranjero querria vender sus órganos', 6, 'respFrases'),
('¿QUIÉN SE UNIRÍA A UNA MANIFESTACIÓN POLÍTICA EN OTRO PAÍS?', ' ', ' ', ' ', ' ', 6, 'respJug'),
('DIBUJA A nombreJug CON EL OBJETO QUE LLEVARÍA SIEMPRE A CUALQUIER VIAJE', ' ', ' ', ' ', ' ', 6, 'respFoto');


/*
      TOTAL PREGUNTAS DE ACAMPADA: 78
      TOTAL PREGUNTAS DE COLEGIO: 75
      TOTAL PREGUNTAS DE PLAYA: 42
      TOTAL PREGUNTAS DE POLICIA: 50
      TOTAL PREGUNTAS DE DEPORTES: 36
      TOTAL PREGUNTAS DE VIAJE: 33
      TOTAL DE PREGUNTAS: 314
*/